### ISSUE TITLE
Implement Stash backup system with a remote endpoint.

### ISSUE THREAD

**Issue by sfxworks** [mcserverhosting-net/charts#2]
https://github.com/appscode/stash

Likely include stash sidecar

**Comment by sfxworks** [comment]
Database test.
```
kind: Restic
metadata:
  name: s3-restic
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-database-mysql
  fileGroups:
  - path: /var/lib
    retentionPolicyName: 'keep-last-60'
  backend:
    s3:
      endpoint: 'swift.endpoint.net'
      bucket: stash
      prefix: main
    storageSecretName: s3-secret
  schedule: '@midnight'
  volumeMounts:
  - mountPath: /var/lib
    name: mysql
  retentionPolicies:
  - name: 'keep-last-60'
    keepLast: 60
    prune: true
```

```
kubectl create secret generic s3-secret -n database \
--from-literal=RESTIC_PASSWORD=redacted \
--from-literal=AWS_ACCESS_KEY_ID=redacted \
--from-literal=AWSSS_KEY=redacted \
```
